artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  resPath: research
  calcTickers: True
  FETCH_REPO: True


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion
  TRANSFORM_DATA: True


model_trainer:
  root_dir: artifacts/model_trainer
  num_trials: 10
  cv: 3
  data_path: artifacts/data_transformation
  mlflow_uri: "http://127.0.0.1:5000"   #"http://34.93.200.115:5000"
  hpo_exp_rf: "random-forest-hyperParamTune v1"
  hpo_exp_xgb: "xgBoost-hyperParamTune v1"
  trainModel: True
  


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation
  top_n: 5
  ml_uri: "http://127.0.0.1:5000"   #"http://34.93.200.115:5000"
  hpo_exp_rf: "random-forest-hyperParamTune v1"
  hpo_exp_xgb: "xgBoost-hyperParamTune v1"
  exp_name: "best-models v1"
  trainModel: True
  # rf_params: ['max_depth', 'n_estimators', 'min_samples_split', 'min_samples_leaf', 'random_state']
